filters:
  - type: "data_cleaning.annotation_standard"
    parameters:
      bounding_box_format: "XYXY"
      bounding_box_coordinate_system: "Continuous"

datasets:
  #- name: "GOT10k"
  #  type: "SOT"
  #  splits:
  #    - "test"

  - name: "LaSOT"
    type: "SOT"
    splits:
      - "test"

  - name: "TrackingNet"
    type: "SOT"
    splits:
      - "test"

  #- name: "UAV123"
  #  type: "SOT"

